import {
	BufferTarget,
	CanvasSource,
	Output,
	QUALITY_HIGH,
	WebMOutputFormat,
	canEncodeVideo,
} from "mediabunny";

// Encodes frames drawn by `drawFrame` into a WebM with an alpha channel
// (VP9, falling back to VP8), so graphics generated by Claude keep a
// transparent background when layered over the footage.

export async function encodeAlphaVideo({
	width,
	height,
	fps,
	frameCount,
	name,
	drawFrame,
}: {
	width: number;
	height: number;
	fps: number;
	frameCount: number;
	name: string;
	drawFrame: (options: {
		ctx: OffscreenCanvasRenderingContext2D;
		index: number;
		time: number;
	}) => Promise<void>;
}): Promise<File> {
	// Encoders want even dimensions.
	const w = Math.max(2, Math.round(width / 2) * 2);
	const h = Math.max(2, Math.round(height / 2) * 2);
	const canvas = new OffscreenCanvas(w, h);
	const ctx = canvas.getContext("2d", { alpha: true });
	if (!ctx) throw new Error("Could not create a drawing surface.");

	const codec = (await canEncodeVideo("vp9", { width: w, height: h }))
		? "vp9"
		: "vp8";
	const output = new Output({
		format: new WebMOutputFormat(),
		target: new BufferTarget(),
	});
	const source = new CanvasSource(canvas, {
		codec,
		bitrate: QUALITY_HIGH,
		alpha: "keep",
		keyFrameInterval: 1,
	});
	output.addVideoTrack(source, { frameRate: fps });
	await output.start();

	for (let index = 0; index < frameCount; index++) {
		const time = index / fps;
		ctx.clearRect(0, 0, w, h);
		await drawFrame({ ctx, index, time });
		await source.add(time, 1 / fps);
	}
	await output.finalize();

	const buffer = output.target.buffer;
	if (!buffer) throw new Error("Encoding produced no data.");
	return new File([buffer], `${name}.webm`, { type: "video/webm" });
}
